# Generated by Django 2.2.6 on 2019-12-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_correct',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_number',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
