# Generated by Django 2.2.6 on 2019-12-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1test', '0005_auto_20191219_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='kinds',
            field=models.CharField(choices=[('KN', 'Khái niệm'), ('QT', 'Qui tắc'), ('TD', 'Tốc độ'), ('NV', 'Nghiệp vụ'), ('VH', 'Văn hóa'), ('KT', 'Kỹ thuật'), ('CT', 'Cấu tạo'), ('BB', 'Biển báo'), ('SH', 'Sa hình')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
