# Generated by Django 2.2.6 on 2019-12-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1test', '0007_auto_20191219_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='time',
            new_name='exam_time',
        ),
    ]
