# Generated by Django 2.2.6 on 2019-12-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1test', '0008_auto_20191219_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_times',
            field=models.IntegerField(default=20),
        ),
    ]
