# Generated by Django 2.2.6 on 2019-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1test', '0009_auto_20191219_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='A1', max_length=255),
        ),
    ]
