# Generated by Django 2.2.6 on 2019-12-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kind',
            field=models.CharField(choices=[('KN', 'Khái niệm'), ('QT', 'Qui tắc'), ('TD', 'Tốc độ'), ('NV', 'Nghiệp vụ'), ('VH', 'Văn hóa'), ('KT', 'Kỹ thuật'), ('CT', 'Cấu tạo'), ('BB', 'Biển báo'), ('SH', 'Sa hình')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
