# Generated by Django 2.2.6 on 2019-12-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_blog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
